---
# tasks file for role-aws-configs

- name: Install general deps
  package:
    name: "{{ item }}"
    state: present
  with_items: 
    - unzip
    - python-pip
    - python-setuptools
  tags: 
    - moodle

# CloudFormation agent
- name: Create /opt/aws/bin/ directory
  file: 
    path: "/opt/aws/bin/"
    state: directory
  tags: 
    - moodle
- name: CFN Bootstrap | Unarchive aws-cfn-bootstrap
  unarchive:
    src: https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
    dest: /opt/aws/bin
    remote_src: true
  tags: 
    - moodle
- name: CFN Bootstrap | Install CFN Bootstrap Module
  command: python /usr/lib/python2.7/dist-packages/easy_install.py --script-dir /opt/aws/bin https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
  tags: 
    - moodle

 # CloudWatch agent
- name: Download aws-cloudwatch-agent.deb file
  get_url:
    url: "https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb"
    dest: "/tmp/cloudwatch-agent.deb"
  tags: 
    - moodle
- name: Install aws-cloudwatch-agent.deb
  apt:
    deb: "/tmp/cloudwatch-agent.deb"
    state: present 
  tags: 
    - moodle

# EFS Utils
- name: Install build dependencies
  package:
    name: binutils
    state: present
  tags: 
    - moodle
- name: Download and unpack source from offical Github repo
  unarchive:
    src: "https://github.com/aws/efs-utils/archive/master.zip"
    dest: "/tmp"
    list_files: yes  # Includes destination folder name
    remote_src: yes
  register: efs_utils_archive
  tags: 
    - moodle
- name: Store location of unarchived source dir
  set_fact:
    efs_utils_source_dir: "{{ efs_utils_archive.dest }}/{{ efs_utils_archive.files[0] }}"
  tags: 
    - moodle
- name: Build EFS deb package
  shell: ./build-deb.sh
  args:
    chdir: "{{ efs_utils_source_dir }}"
    creates: build/amazon-efs-utils*deb
  tags: 
    - moodle
- name: Install EFS deb package
  shell: apt -y install ./build/amazon-efs-utils*deb
  args:
    chdir: "{{ efs_utils_source_dir }}"
  tags: 
    - moodle

# Clean tmp
- name: Remove cloudwatch deb
  file:
    path: /tmp/cloudwatch-agent.deb
    state: absent
  notify:
    - restart apache
  tags: 
    - common
- name: Remove efs
  file:
    path: "{{ efs_utils_archive.dest }}"
    state: absent
  notify:
    - restart apache
  tags: 
    - common